[server]
headless = true
maxUploadSize = 10
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#5367d9"
backgroundColor = "#f6f8fc"
secondaryBackgroundColor = "#ffffff"
textColor = "#172033"
font = "sans serif"
